site_name: Jetson Orin Nano Super Workshop
site_description: A hands-on workshop for NVIDIA Jetson Orin Nano Super
site_author: Ajeet Singh Raina
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
    - Prerequisites: getting-started/prerequisites.md
    - Hardware Setup: getting-started/hardware-setup.md
    - Software Setup: getting-started/software-setup.md
  - Labs:
    - 'Lab 1: Basic Setup & Configuration':
      - Overview: labs/lab1/overview.md
      - Initial Setup: labs/lab1/setup.md
      - Power Modes: labs/lab1/power-modes.md
      - Verification: labs/lab1/verification.md
    - 'Lab 2: AI Model Optimization':
      - Overview: labs/lab2/overview.md
      - Model Selection: labs/lab2/model-selection.md
      - TensorRT Optimization: labs/lab2/tensorrt-optimization.md
      - Performance Testing: labs/lab2/performance-testing.md
    - 'Lab 3: Sensor Integration':
      - Overview: labs/lab3/overview.md
      - BME680 Setup: labs/lab3/bme680-setup.md
      - Data Collection: labs/lab3/data-collection.md
      - AI Integration: labs/lab3/ai-integration.md
  - Resources:
    - Troubleshooting: resources/troubleshooting.md
    - FAQ: resources/faq.md
    - References: resources/references.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ajeetraina/jetson-orin-nano-super-guide
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ajeetsraina
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
