site_name: Jetson Orin Nano Super Guide
site_description: Comprehensive guide for NVIDIA Jetson Orin Nano
site_author: Community Contributors

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - footnotes
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: quick-start.md
    - Hardware Setup: hardware-setup.md
    - Software Setup: software-setup.md
  - Labs:
    - Overview: labs/index.md
    - Getting Started Labs: labs/getting-started.md
    - Computer Vision Labs: labs/computer-vision.md
    - TensorRT Labs: labs/tensorrt.md
    - Edge AI Labs: labs/edge-ai.md
    - Performance Labs: labs/performance.md
  - Development:
    - Environment Setup: development/environment.md
    - Best Practices: development/best-practices.md
    - Troubleshooting: development/troubleshooting.md
  - Resources:
    - Documentation: resources/documentation.md
    - Community: resources/community.md
    - FAQ: resources/faq.md

repo_name: ajeetraina/jetson-orin-nano-super-guide
repo_url: https://github.com/ajeetraina/jetson-orin-nano-super-guide
edit_uri: edit/main/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ajeetraina/jetson-orin-nano-super-guide
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/ajeetraina/jetson-orin-nano
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

copyright: Copyright &copy; 2024 Community Contributors